export { default as Star } from "./shapes/star.svg";
export { default as SevenStar } from "./shapes/7star.svg";
export { default as square } from "./shapes/square.svg";
export { default as triangle } from "./shapes/triangle.svg";
export { default as circle } from "./shapes/circle.svg";
export { default as GradBGHero } from "./images/grad-bg-hero.png";
export { default as AlbieTheGuide } from "./images/albie-the-guide.png";
export { default as nx4_the_mascot } from "./images/nx4-the-mascot.png";
export { default as AboutUSCover } from "./images/about-us-cover.png";
